import { prisma } from "../lib/prisma";
import { DriveProvider } from "../providers/DriveProvider";
import { DocsProvider } from "../providers/DocsProvider";
import { EmailProvider } from "../providers/EmailProvider";
import { notify } from "../notifications/notifier";
import { buildPlaceholderRequests } from "./placeholderRequests";
import { TEMPLATE_ID, TARGET_FOLDER_ID, buildDriveUrl } from "./driveConfig";

export interface WorkerDependencies {
  driveProvider: DriveProvider;
  docsProvider: DocsProvider;
  emailProvider: EmailProvider;
}

// LLD §5 — worker pseudocode, one attempt.
export async function processInvoiceJob(invoiceId: string, deps: WorkerDependencies): Promise<void> {
  const invoice = await prisma.invoice.findUniqueOrThrow({
    where: { id: invoiceId },
    include: { sheetRow: true, resource: true },
  });

  await prisma.invoice.update({ where: { id: invoiceId }, data: { generationStatus: "PROCESSING" } });

  // LLD §6: driveFileId is persisted immediately after copy, before fill/
  // share — on retry, if it already exists, the copy step is skipped.
  let driveFileId = invoice.driveFileId;
  if (!driveFileId) {
    driveFileId = await deps.driveProvider.copyTemplate(TEMPLATE_ID, TARGET_FOLDER_ID);
    await prisma.invoice.update({ where: { id: invoiceId }, data: { driveFileId } });
  }

  const invoiceDate = invoice.invoiceDate ?? new Date();

  const requests = buildPlaceholderRequests({
    invoice: { invoiceNo: invoice.invoiceNo, amount: Number(invoice.amount), invoiceDate },
    resource: invoice.resource,
    sheetRow: { projectName: invoice.sheetRow.projectName, hours: Number(invoice.sheetRow.hours), rate: Number(invoice.sheetRow.rate) },
  });
  await deps.docsProvider.batchUpdate(driveFileId, requests);
  await deps.driveProvider.shareWithEmail(driveFileId, invoice.resource.email);

  await prisma.invoice.update({
    where: { id: invoiceId },
    data: {
      generationStatus: "GENERATED",
      approvalStatus: "PENDING",
      driveDocUrl: buildDriveUrl(driveFileId),
      invoiceDate,
    },
  });

  // HLD §7: "Payout generated | Resource | End of successful generation job."
  // Renamed from INVOICE_GENERATED (LLD §0.9) — no document link included;
  // the resource doesn't see the invoice until gate 1 (amount confirmation)
  // passes, even though the document itself is fully generated by now.
  await notify(deps.emailProvider, "PAYOUT_GENERATED", invoice.resource.email, "invoice", invoiceId);
}

// LLD §5: "BullMQ retries (3 attempts, exponential backoff). After
// exhausting retries, catch and set generationStatus = 'FAILED',
// errorMessage." Real backoff/scheduling is Phase 7 (real BullMQ) — this
// drives the same number of attempts synchronously so the failure-handling
// behavior is testable now; Phase 7's real worker can call this directly.
export async function processInvoiceJobWithRetries(
  invoiceId: string,
  deps: WorkerDependencies,
  maxAttempts = 3
): Promise<void> {
  let lastError: unknown;
  for (let attempt = 1; attempt <= maxAttempts; attempt++) {
    try {
      await processInvoiceJob(invoiceId, deps);
      return;
    } catch (err) {
      lastError = err;
    }
  }
  await prisma.invoice.update({
    where: { id: invoiceId },
    data: {
      generationStatus: "FAILED",
      errorMessage: lastError instanceof Error ? lastError.message : String(lastError),
    },
  });
}
